---
- hosts: all
  become: yes

  vars_files:
    - vault.yml

  roles:
    - ansible-os-hardening
    - ansible-ssh-hardening

  tasks:  
    - include: tasks/setup_file2ban.yml
    - include: tasks/secure_ssh.yml

  handlers:
    - include: handlers.yml