---
- hosts: all
  become: yes
  vars_files:
    - vault.yml
  roles:
    - ansible-papertrail
  vars:
    papertrail_host: "{{ vault_papertrail_host }}"
    papertrail_port: "{{ vault_papertrail_port }}"