---
- hosts: all
  become: yes

  vars_files:
    - vault.yml

  roles:
    - newrelic
    - ansible-papertrail
    - ansible-datadog
    - ansible-syncthing
    - ansible-netdata

  vars:
    newrelic_license_key: "{{ vault_newrelic_key }}"
    papertrail_host: "{{ vault_papertrail_host }}"
    papertrail_port: "{{ vault_papertrail_port }}"
    datadog_api_key: "{{ vault_datadog_key }}"
    syncthing_user: "{{ vault_new_user }}"
    syncthing_home: "/home/{{ vault_new_user }}"
    syncthing_use_ufw: false
    netdata_registry_enabled: false

  tasks:
    - include: tasks/set_file_permissions.yml
    - include: tasks/create_user.yml
    - include: tasks/setup_nginx.yml
    - include: tasks/setup_rtorrent.yml
    - include: tasks/run_updates.yml

  handlers:
    - include: handlers.yml