---

- name: Load variables
  include_vars: "vault.yml"
  no_log: true

- name: Remove sudo group rights
  lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent validate='visudo -cf %s'

- name: Create {{ vault_new_user }} user account
  user: name={{ vault_new_user }} password={{ vault_new_user_password }} shell=/bin/bash state=present #generate_ssh_key=yes

- name: Add user {{ vault_new_user }} to sudoers
  action: lineinfile dest=/etc/sudoers regexp="^{{ vault_new_user }} ALL" line="{{ vault_new_user }} ALL=(ALL) ALL" state=present validate="visudo -cf %s"

- name: Ensure public key is in authorized_keys
  authorized_key:
    key: "{{ vault_auth_public_key }}"
    user: "{{ vault_new_user }}"